//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleaMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DateOfHire
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_DateOfHire()
        {
            this.tbl_Shop = new HashSet<tbl_Shop>();
        }
    
        public int id_dateofhire { get; set; }
        public Nullable<System.DateTime> doh_startday { get; set; }
        public Nullable<System.DateTime> doh_expirationdate { get; set; }
        public string doh_note { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Shop> tbl_Shop { get; set; }
    }
}
