//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FleaMarket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Shop()
        {
            this.tbl_Product = new HashSet<tbl_Product>();
            this.tbl_ProductMore = new HashSet<tbl_ProductMore>();
        }
    
        public int id_shop { get; set; }
        public string shop_name { get; set; }
        public string shop_address { get; set; }
        public string shop_introduce { get; set; }
        public string shop_phone { get; set; }
        public string shop_avatar { get; set; }
        public string shop_background { get; set; }
        public Nullable<int> id_account { get; set; }
        public Nullable<int> id_dateofhire { get; set; }
    
        public virtual tbl_Account tbl_Account { get; set; }
        public virtual tbl_DateOfHire tbl_DateOfHire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Product> tbl_Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProductMore> tbl_ProductMore { get; set; }
    }
}
